version: "3"

services:
  tasks-db-prod:
    container_name: tasks-db-prod
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "admin123"
      MYSQL_DATABASE: "tasksdb"
    ports:
      - "3306:3306"
    networks:
      - tasks-net
    volemes:
      - tasks-volume: /var/lib/mysql

networks:
  tasks-net:
volemes:
  tasks-volume:
